# Generated by Django 3.1.2 on 2020-10-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0003_auto_20201020_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='No bio available...'),
        ),
    ]
